//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB_FINAL_EV.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BloodBankEveningEntities : DbContext
    {
        public BloodBankEveningEntities()
            : base("name=BloodBankEveningEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BloodGroup> BloodGroups { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<District> Districts { get; set; }
        public DbSet<Donner> Donners { get; set; }
        public DbSet<Post> Posts { get; set; }
        public DbSet<Requisition> Requisitions { get; set; }
        public DbSet<Thana> Thanas { get; set; }
    }
}
