//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB_FINAL_EV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodGroup
    {
        public BloodGroup()
        {
            this.Donners = new HashSet<Donner>();
            this.Requisitions = new HashSet<Requisition>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<Donner> Donners { get; set; }
        public virtual ICollection<Requisition> Requisitions { get; set; }
    }
}
