//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BB_FINAL_EV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.Donners = new HashSet<Donner>();
            this.Requisitions = new HashSet<Requisition>();
            this.Thanas = new HashSet<Thana>();
        }
    
        public int DistrictID { get; set; }
        public string DistrictName { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<Donner> Donners { get; set; }
        public virtual ICollection<Requisition> Requisitions { get; set; }
        public virtual ICollection<Thana> Thanas { get; set; }
    }
}
